"""Add subtitle column to Note table.

Revision ID: 3485c7689032
Revises: aa7db45de06e
Create Date: 2025-09-03 17:29:00.329743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3485c7689032'
down_revision = 'aa7db45de06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
